# this is an example config file. to connect to a snowflake account ensure you have a file named .streamlit/secrets.toml with the proper information filled out.

[snowflake]
user = "xxx"
password = "xxx"
account = "xxx"
warehouse = "xxx"
database = "xxx"
schema = "xxx"